### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by olebedev** [timbertson/runix#6] opened 2024-01-03 03:56 UTC
Hi there 👋 
Thanks for such an inspiring project. 

I am running into the installation issue:
```
λ curl -sSL https://raw.githubusercontent.com/timbertson/runix/main/bootstrap.sh | bash
[runix-bootstrap] Downloading ...
[runix-bootstrap] extracting to /tmp/runix-bootstrap ...
tar: Error opening archive: Unrecognized archive format

```

I guess it's because in [this](https://github.com/timbertson/runix/blob/main/bootstrap.sh#L4) line I get 
```
λ echo "$(uname -m)-$(uname -s)"
arm64-Darwin

```

But the release page https://github.com/timbertson/runix/releases doesn't provide `runix-arm64-Darwin.tgz` but `runix-aarch64-Darwin.tgz`.

The fix would be either add a condition into the `bootstrap.sh` so it constructs the name that does exist at the release page or simple upload that `runix-arm64-Darwin.tgz` asset to the release page.

I am happy to make a change to the `bootstrap.sh` script if you prefer it done in that way. Please let me know what are your thoughts.

Kind regards,
Oleg

**Comment by olebedev** [comment] 2024-01-03 04:04
The attempt to use `LOCAL_BOOTSTRAP` env var is also unsuccessful.

```
λ curl -sSL "https://github.com/timbertson/runix/releases/download/bootstrap/runix-aarch64-Darwin.tgz" -o ./bootstrap/runix-arm64-Darwin.tgz
λ export LOCAL_BOOTSTRAP=./bootstrap
λ curl -sSL https://raw.githubusercontent.com/timbertson/runix/main/bootstrap.sh | bash
[runix-bootstrap] extracting to /tmp/runix-bootstrap ...
[runix-bootstrap] Running self-install ...
main: line 15: 34350 Killed: 9               "$TMP_DEST/runix" --self-install "$TMP_DEST/wrapper"

λ ls -la ~/.cache/runix
ls: /Users/olebedev/.cache/runix: No such file or directory

λ ls -la /tmp/runix-bootstrap
total 8
drwxr-xr-x   5 olebedev  wheel  160  3 Jan 15:00 .
drwxrwxrwt  17 root      wheel  544  3 Jan 15:00 ..
lrwxr-xr-x   1 olebedev  wheel   86 24 Jan  2023 runix -> store/db3ranx5x74l50dyg6n5zwl45m1jc9ww-rust_runix-0.1.0-aarch64-apple-darwin/bin/runix
drwxr-xr-x   8 olebedev  wheel  256 24 Jan  2023 store
-rwxr-xr-x   1 olebedev  wheel  331 24 Jan  2023 wrapper
```

**Comment by olebedev** [comment] 2024-01-03 04:35
Then I tried:
```
λ nix-env -i -f https://github.com/timbertson/runix/archive/main.tar.gz
trace: [niv]: providing nixpkgs from tarball
trace: [niv]: providing fenix from tarball
trace: real cf: /nix/store/1h3qc5844jwsjb62sg7j4mrj5gn4zxc4-apple-framework-CoreFoundation-11.0.0
trace: [niv]: providing fetlock from tarball
fatal: '/nix/store/xdv0cvsy0gigam8wfl0537xfw46822jn-source' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)

```

no success either.

**Comment by olebedev** [comment] 2024-01-03 04:52
Cloning the repo and 
```
nix-env -i -f ./default.nix
```

worked to me. But I guess the whole idea of the project is to don't have nix onboard so it's bit of a broken setup now anyway.

I am happy to contribute to make that work. Let me know if you need any help with that.

Cheers,
Oleg

**Comment by olebedev** [comment] 2024-01-03 04:57
Ah, it doesn't work after I get the executable into my `$PATH` finally. I get process exits with non zero code:
```
λ nix-instantiate --eval -A jq.outPath '<nixpkgs>'
"/nix/store/38hrq70jzqsq81v7gim7j3q45955186l-jq-1.7-bin"

λ runix --require 38hrq70jzqsq81v7gim7j3q45955186l-jq-1.7-bin jq --help
[1]    58525 killed     runix --require 38hrq70jzqsq81v7gim7j3q45955186l-jq-1.7-bin jq --help

```

**Comment by timbertson** [comment] 2024-01-04 02:26
Thanks for the report. I think I built those packages on an intel mac, cross-compiled for arm. Now I have an arm mac, and I get the same result out of `uname` as you do. I'll try to reproduce and see what's going on...

**Comment by timbertson** [comment] 2024-01-29 22:29
Finally got a chance to look into this properly. I think the aarch64 -> arm64 part is easy, runix can just match what `uname` does for consistency: #7 .

The `killed` thing is more mysterious. I get the same on a local `nix-build` result. But a binary built through `cargo` works correctly. I can also run the nix-build binary via `lldb`, and that works. So the binary seems mostly valid, my main suspicion right now is that it's issues with code signing, and it's not about arm64 but simply about an upgraded macOS since I last tested it.

**Comment by timbertson** [comment] 2024-01-29 23:21
Reopening for the `killed` issue, and I won't be able to actually upload a new bootstrap assets until that's fixed.

**Comment by olebedev** [comment] 2024-01-30 23:09
Nice one, thanks for the fix in the naming convention 👍 

> my main suspicion right now is that it's issues with code signing, and it's not about arm64 but simply about an upgraded macOS since I last tested it.

I am not too sure, but I think it's not the case here, otherwise none of downloaded from the binary cache executables will work on the new macOS.

I have a suspicious that it's all about the cross platform builds in Nix. As you mentioned, the vanilla cargo build works fine without code signing procedure, right? If so I would guess that Nix build would have worked as well, but it's not.

I am thinking about how we can verify the above. If you have a chance to run Nix build on your x86_64 machine with that latest macOS that would give us understanding that it's the OS related problem, at least. Ah, this can actually be done in Github Actions, [if it's not already](https://github.com/timbertson/runix/blob/main/.github/workflows/ci.yml#L10)? I see the test failures [here](https://github.com/timbertson/runix/actions/runs/7703589522/job/20994284956), but doesn't seem related, right?

I am wondering, if we can run all the builds on Github Actions natively instead of [building them all cross-platform](https://github.com/timbertson/runix/blob/main/.github/workflows/ci.yml#L33-L34) and later upload these natively built artifacts to the release page?

**Comment by timbertson** [comment] 2024-01-31 01:40
Yeah I dunno for sure. I'm thinking it's less about being unsigned, and more about maybe some bugs in the way the executable is constructed (related to signing). I saw some issues around about rust linking causing similar issues which gave me that idea. The cross-building is not relevant here, it gets skipped when targetPlatform == hostPlatform so this is just a normal nix build.

I'm currently upgrading nixpkgs to 23.11 and it's looking good on this front at least (other issues remain, which I'm working on 😅 ). Perhaps rust binaries from 22.05 (the current pin) _were_ always broken on MacOS Ventura, but nobody noticed because it hadn't been released.

I really want to keep the release process single-machine if I can, it's just so much easier to work on issues if I'm not jumping between machines or waiting on GH builds. So fingers crossed the update just fixes it 🤞

**Comment by olebedev** [comment] 2024-01-31 03:47
> The cross-building is not relevant here, it gets skipped when targetPlatform == hostPlatform so this is just a normal nix build.

Ah, gotcha.

> I really want to keep the release process single-machine if I can, it's just so much easier to work on issues if I'm not jumping between machines or waiting on GH builds. So fingers crossed the update just fixes it 🤞

I see, agree that operate on a single machine is tempting to avoid the mess with orchestration. Not everyone that lucky to be able to do that, though. But with Nix we have a hope. Fingers crossed!

**Comment by timbertson** [comment] 2024-02-02 03:02
OK I've got my head around most of the problems now I think, I'll close this issue as I've opened more specific issues now:
 - #8
 - #9
 - #10

**Closed by timbertson** 2024-02-02 03:02 UTC

**Comment by timbertson** [comment] 2024-02-04 11:26
OK, the bootstrap assets should work now on arm64 (works for mw now 🤞) .

**Comment by olebedev** [comment] 2024-02-04 23:05
That's awesome, I tried the latest version and it worked as expected 👍 Thank you for fixing it up!

![so-good](https://github.com/timbertson/runix/assets/848535/30712f01-9278-46fd-beeb-ae87968195f4)
